#!/usr/bin/env bash
# Compiles all TODO objects on pub400.com in the dependency order documented
# in AGENTS.md. Deletes each object first (ignoring failure, e.g. first run)
# so recompiles are clean. Adds DBGVIEW(*SOURCE) to CRTBNDRPG for source-level
# debugging via the IBM i Debug extension.
set -euo pipefail

USER="${1:?usage: ibmi-compile.sh <pub400-username>}"
HOST="pub400.com"

try() { ssh "$USER@$HOST" "system \"$1\"" || true; }
run() { echo ">>> $1"; ssh "$USER@$HOST" "system \"$1\""; }

try "DLTF FILE(TODO/TODOPF)"
run "CRTPF FILE(TODO/TODOPF) SRCFILE(TODO/QDDSSRC) SRCMBR(TODOPF)"

try "DLTF FILE(TODO/TODOLF)"
run "CRTLF FILE(TODO/TODOLF) SRCFILE(TODO/QDDSSRC) SRCMBR(TODOLF)"

try "DLTF FILE(TODO/TODODSPPF)"
run "CRTDSPF FILE(TODO/TODODSPPF) SRCFILE(TODO/QDDSSRC) SRCMBR(TODODSPPF)"

try "RMVBNDDIRE BNDDIR(TODO/TODOBND) OBJ((TODO/TODOBL *SRVPGM))"
try "DLTBNDDIR BNDDIR(TODO/TODOBND)"
run "CRTBNDDIR BNDDIR(TODO/TODOBND)"

try "DLTSRVPGM SRVPGM(TODO/TODOBL)"
try "DLTMOD MODULE(TODO/TODOBL)"
run "CRTRPGMOD MODULE(TODO/TODOBL) SRCFILE(TODO/QRPGLESRC) SRCMBR(TODOBL) DBGVIEW(*SOURCE)"
run "CRTSRVPGM SRVPGM(TODO/TODOBL) MODULE(TODO/TODOBL)"
run "ADDBNDDIRE BNDDIR(TODO/TODOBND) OBJ((TODO/TODOBL *SRVPGM))"

try "DLTPGM PGM(TODO/TODOMAIN)"
run "CRTBNDRPG PGM(TODO/TODOMAIN) SRCFILE(TODO/QRPGLESRC) SRCMBR(TODOMAIN) BNDDIR(TODO/TODOBND) DBGVIEW(*SOURCE)"

try "DLTSRVPGM SRVPGM(TODO/TODOTEST)"
try "DLTMOD MODULE(TODO/TODOTEST)"
run "CRTRPGMOD MODULE(TODO/TODOTEST) SRCFILE(TODO/QRPGLESRC) SRCMBR(TODOTEST) DBGVIEW(*SOURCE)"
run "CRTSRVPGM SRVPGM(TODO/TODOTEST) MODULE(TODO/TODOTEST) BNDDIR(TODO/TODOBND) BNDSRVPGM(RPGUNIT/RUCRTTST)"

echo ">>> Compile complete."
